{% set version = "0.1.7" %}

package:
  name: dante_tir
  version: {{ version }}

source:
  url: https://github.com/kavonrtep/dante_tir/archive/refs/tags/{{ version }}.tar.gz
  sha256: 49f957a5dccc02535660a08baa8e5e4f14c6f97fc26d4666d5144420eac4d987
requirements:
  run:
    - r-optparse
    - blast
    - cap3
    - r-rbeast
    - bioconductor-biostrings
    - bioconductor-bsgenome
    - bioconductor-rtracklayer
    - python>=3.6.0
    - mmseqs2>=14
test:
  commands:
    - dante_tir.py --help

about:
  dev_url: https://github.com/kavonrtep/dante_tir
  license: GNU GPL v3
  license_file: LICENSE
  summary: DANTE_TIR is a program for finding full-length TIR transposons using Domain based ANnotation of Transposable elements

extra:
  copy_test_source_files: true
  final: true

