{% set version = "0.1.3" %}

package:
  name: dante_tir
  version: {{ version }}

source:
  url: https://github.com/kavonrtep/dante_tir/archive/refs/tags/{{ version }}.tar.gz
  sha256: 43165d0a8e6d708427879e2a133f049aeae36fdb39c714074745bc44a58633f8
requirements:
  run:
    - r-optparse
    - blast
    - cap3
    - r-rbeast
    - bioconductor-biostrings
    - bioconductor-bsgenome
    - bioconductor-rtracklayer
    - python>=3.6.0
    - mmseqs2>=14
test:
  commands:
    - dante_tir.py --help

about:
  dev_url: https://github.com/kavonrtep/dante_tir
  license: GNU GPL v3
  license_file: LICENSE
  summary: DANTE_TIR is a program for finding full-length TIR transposons using Domain based ANnotation of Transposable elements

extra:
  copy_test_source_files: true
  final: true

