{% set version = "1.1" %}

package:
  name: tidecluster
  version: {{ version }}

source:
  url: https://github.com/kavonrtep/TideCluster/archive/refs/tags/{{ version }}.tar.gz
  sha256: 5dd0c3c13e12f72c6b8ff4593f8d8b4bc3118e2bd663c6ea9119f943bbb31131
requirements:
  run:
    - TideHunter=1.4.3
    - blast
    - mmseqs2
    - python>=3.6
    - networkx
    - repeatmasker=4.1.2.p1
    - r-optparse
    - r-igraph
    - bioconductor-biostrings
    - r-scales
    - r-hwriter
    - r-r2html
    - r-plyr
    - r-dplyr
    - mafft
test:
  commands:
    - TideCluster.py --help

about:
  dev_url: https://github.com/kavonrtep/TideCluster
  license: GPL-3.0-only
  license_file: LICENSE
  summary: TideCluster is wrapper for Tidehunter and is intended for identifying tandem repeats in genome assemblies

extra:
  copy_test_source_files: true
  final: true
