{% set version = "0.0.5" %}

package:
  name: tidecluster
  version: {{ version }}

source:
  url: https://github.com/kavonrtep/TideCluster/archive/refs/tags/{{ version }}.tar.gz
  sha256: aedb024d4200ed7d2bdf55600afe6c98b463d2dd130a684d16a8c484ebd36027
requirements:
  run:
    - TideHunter=1.4.3
    - blast
    - mmseqs2
    - python>=3.6
    - networkx
    - repeatmasker
    - r-optparse
    - r-igraph
    - bioconductor-biostrings
    - r-scales
    - r-hwriter
    - r-r2html
    - r-plyr
    - r-dplyr
    - mafft
test:
  commands:
    - TideCluster.py --help

about:
  dev_url: https://github.com/kavonrtep/TideCluster
  license: GNU GPL v3
  license_file: LICENSE
  summary: TideCluster is wrapper for Tidehunter and is intended for identifying tandem repeats in genome assemblies

extra:
  copy_test_source_files: true
  final: true
