{% set version = "0.0.7" %}

package:
  name: tidecluster
  version: {{ version }}

source:
  url: https://github.com/kavonrtep/TideCluster/archive/refs/tags/{{ version }}.tar.gz
  sha256: 0713a2526311e2d08f709e5ee393d0d8e5407dbbf814035c0a10ac8a361dfaef
requirements:
  run:
    - TideHunter=1.4.3
    - blast
    - mmseqs2
    - python>=3.6
    - networkx
    - repeatmasker=4.1.2.p1
    - r-optparse
    - r-igraph
    - bioconductor-biostrings
    - r-scales
    - r-hwriter
    - r-r2html
    - r-plyr
    - r-dplyr
    - mafft
test:
  commands:
    - TideCluster.py --help

about:
  dev_url: https://github.com/kavonrtep/TideCluster
  license: GNU GPL v3
  license_file: LICENSE
  summary: TideCluster is wrapper for Tidehunter and is intended for identifying tandem repeats in genome assemblies

extra:
  copy_test_source_files: true
  final: true
