{% set version = "1.8.0" %}

package:
  name: tidecluster
  version: {{ version }}

source:
  url: https://github.com/kavonrtep/TideCluster/archive/refs/tags/{{ version }}.tar.gz
  sha256: c489c89069024c750c6bd11047f6401241e674be57452cebd25e8616e63e41e3
requirements:
  run:
    - TideHunter=1.4.3
    - blast
    - mmseqs2
    - python>=3.6
    - networkx
    - repeatmasker=4.1.2.p1
    - r-optparse
    - r-igraph
    - bioconductor-biostrings
    - bioconductor-rtracklayer
    - r-scales
    - r-hwriter
    - r-r2html
    - r-plyr
    - r-dplyr
    - r-jsonlite
    - r-reshape2
    - mafft
    - bedtools
test:
  commands:
    - TideCluster.py --help

about:
  dev_url: https://github.com/kavonrtep/TideCluster
  license: GPL-3.0-only
  license_file: LICENSE
  summary: TideCluster is wrapper for Tidehunter and is intended for identifying tandem repeats in genome assemblies

extra:
  copy_test_source_files: true
  final: true
