{% set version = "0.2.2.2" %}

package:
  name: dante_ltr
  version: {{ version }}

source:
  url: https://github.com/kavonrtep/dante_ltr/archive/refs/tags/{{ version }}.tar.gz
  sha256: 39323d9918969982024bf09a249151dcc763913b878c6039de1a88cc8f2b4ec3
requirements:
  run:
    - r-optparse
    - blast
    - bioconductor-biostrings
    - bioconductor-bsgenome
    - bioconductor-rtracklayer
    - r-dplyr=1.0.7
    - python>=3.6.0
    - tidehunter=1.4.3
    - bedtools>=2.23.0
test:
  commands:
    - dante_ltr --help

about:
  dev_url: https://github.com/kavonrtep/dante_ltr
  license: GNU GPL v3
  license_file: LICENSE
  summary: DANTE_LTR is a program for finding full-length LTR retrotranspsons using Domain based ANnotation of Transposable elements

extra:
  copy_test_source_files: true
  final: true

