{% set version = "0.3.5.3" %}

package:
  name: dante_ltr
  version: {{ version }}

source:
  url: https://github.com/kavonrtep/dante_ltr/archive/refs/tags/{{ version }}.tar.gz
  sha256: bbae18175d9937cfc08ff593ffa09ac6df02249b1c8df865e4fb8e5b403e1f5d
requirements:
  run:
    - r-optparse
    - blast
    - bioconductor-biostrings
    - bioconductor-bsgenome
    - bioconductor-rtracklayer
    - r-dplyr=1.0.7
    - python>=3.6.0
    - tidehunter=1.4.3
    - bedtools>=2.23.0
    - mmseqs2>=14
test:
  commands:
    - dante_ltr --help
    - dante_ltr --version

about:
  dev_url: https://github.com/kavonrtep/dante_ltr
  license: GNU GPL v3
  license_file: LICENSE
  summary: DANTE_LTR is a program for finding full-length LTR retrotranspsons using Domain based ANnotation of Transposable elements

extra:
  copy_test_source_files: true
  final: true

