{% set version = "0.2.8" %}

package:
  name: dante
  version: {{ version }}

source:
  url: https://github.com/kavonrtep/dante/archive/refs/tags/{{ version }}.tar.gz
  sha256 : 3cc98f6815d437c526a0d0cff435fdf15958a6f2022323fe3da78118c9e222e2
requirements:
  run:
    - last=1453
    - numpy=1.24.2
    - python=3.11.0
    - biopython=1.81
    - r-base=4.1.3
test:
  commands:
    - dante --help

about:
  dev_url: https://github.com/kavonrtep/dante
  license: GNU GPL v3
  license_file: LICENCE
  summary: DANTE is a program for identification of transposable elements protein coding sequences using REXdb database

extra:
  copy_test_source_files: true
  final: true

