{% set version = "0.2.2" %}

package:
  name: dante
  version: {{ version }}

source:
  url: https://github.com/kavonrtep/dante/archive/refs/tags/{{ version }}.tar.gz
  sha256 : f2bd34c79f02c10e3d903ad72a2fe0977a93afab0c30b015ccbfc4b04b432d89
requirements:
  run:
    - last=1453
    - numpy=1.24.2
    - python>=3.11.0
    - biopython=1.81
    - r-base=4.1.3
test:
  commands:
    - dante --help

about:
  dev_url: https://github.com/kavonrtep/dante
  license: GNU GPL v3
  license_file: LICENCE
  summary: DANTE is a program for identification of transposable elements protein coding sequences using REXdb database

extra:
  copy_test_source_files: true
  final: true

