{% set version = "0.2.9" %}

package:
  name: dante
  version: {{ version }}

source:
  url: https://github.com/kavonrtep/dante/archive/refs/tags/{{ version }}.tar.gz
  sha256 : 7523ba92eb4e46f69353df618459cbd1ec15c984ef4ed94da82847863bfde65a
requirements:
  run:
    - last=1453
    - numpy=1.24.2
    - python=3.11.0
    - biopython=1.81
    - r-base=4.1.3
test:
  commands:
    - dante --help

about:
  dev_url: https://github.com/kavonrtep/dante
  license: GNU GPL v3
  license_file: LICENCE
  summary: DANTE is a program for identification of transposable elements protein coding sequences using REXdb database

extra:
  copy_test_source_files: true
  final: true

