{% set version = "0.1.9" %}

package:
  name: dante
  version: {{ version }}

source:
  url: https://github.com/kavonrtep/dante/archive/refs/tags/{{ version }}.tar.gz
  sha256 : 0d540fd3a68fe9707ef81b5f27e00c41e284a9b93c4e8167bee5e3aab6120546
requirements:
  run:
    - last>=744
    - numpy
    - python>=3.6.0
    - biopython
    - r-base
test:
  commands:
    - dante --help

about:
  dev_url: https://github.com/kavonrtep/dante
  license: GNU GPL v3
  license_file: LICENCE
  summary: DANTE is a program for identification of transposable elements protein coding sequences using REXdb database

extra:
  copy_test_source_files: true
  final: true

