{% set version = "0.1.7" %}

package:
  name: dante
  version: {{ version }}

source:
  url: https://github.com/kavonrtep/dante/archive/refs/tags/{{ version }}.tar.gz
  sha256 : cc9d516cf502225463021a6d08b701855bcf977427297e4bbd822de6106512a1
requirements:
  run:
    - last>=744
    - numpy
    - python>=3.6.0
    - biopython
    - r-base
test:
  commands:
    - dante --help

about:
  dev_url: https://github.com/kavonrtep/dante
  license: GNU GPL v3
  license_file: LICENCE
  summary: DANTE is a program for identification of transposable elements protein coding sequences using REXdb database

extra:
  copy_test_source_files: true
  final: true

