{% set version = "0.1.4" %}

package:
  name: dante
  version: {{ version }}

source:
  url: https://github.com/kavonrtep/dante/archive/refs/tags/{{ version }}.tar.gz
  sha256 : 77a8daa8d6200eb155578f7328c1acc7125a507d74a6f0ab31ba1b3240953865
requirements:
  run:
    - last>=744
    - numpy
    - python>=3.6.0
    - biopython
    - r-base
test:
  commands:
    - dante --help

about:
  dev_url: https://github.com/kavonrtep/dante
  license: GNU GPL v3
  license_file: LICENCE
  summary: DANTE is a program for identification of transposable elements protein coding sequences using REXdb database

extra:
  copy_test_source_files: true
  final: true

