{% set version = "0.1.3" %}

package:
  name: dante
  version: {{ version }}

source:
  url: https://github.com/kavonrtep/dante/archive/refs/tags/{{ version }}.tar.gz
  sha256: da54f2724165b6d6c8680d4eadb85963b1f2634580c2fc62db2219d4d095d229
requirements:
  run:
    - last>=744
    - numpy
    - python>=3.6.0
    - biopython
test:
  commands:
    - dante --help

about:
  dev_url: https://github.com/kavonrtep/dante
  license: GNU GPL v3
  license_file: LICENCE
  summary: DANTE is a program for identification of transposamble elements protein coding sequences using REXdb database

extra:
  copy_test_source_files: true
  final: true

