{% set version = "0.2.3" %}

package:
  name: dante
  version: {{ version }}

source:
  url: https://github.com/kavonrtep/dante/archive/refs/tags/{{ version }}.tar.gz
  sha256 : a2062e2043ccb0dd613c0b6f8adb1bdb8a05c63933c9ce7151e33727a184cbc3
requirements:
  run:
    - last=1453
    - numpy=1.24.2
    - python=3.11.0
    - biopython=1.81
    - r-base=4.1.3
test:
  commands:
    - dante --help

about:
  dev_url: https://github.com/kavonrtep/dante
  license: GNU GPL v3
  license_file: LICENCE
  summary: DANTE is a program for identification of transposable elements protein coding sequences using REXdb database

extra:
  copy_test_source_files: true
  final: true

